ALTER DATABASE PartitionedData
ADD FILEGROUP Sales2009

ALTER DATABASE PartitionedData
ADD FILEGROUP Sales2010

ALTER DATABASE PartitionedData
ADD FILEGROUP Sales2011

ALTER DATABASE PartitionedData
ADD FILEGROUP Sales2012

ALTER DATABASE PartitionedData
ADD FILEGROUP Sales2013

ALTER DATABASE PartitionedData
ADD FILEGROUP Sales2014

ALTER DATABASE PartitionedData
ADD FILEGROUP Sales2015

ALTER DATABASE PartitionedData
ADD FILEGROUP Sales2016

ALTER DATABASE PartitionedData
ADD FILEGROUP Sales2017

ALTER DATABASE PartitionedData
ADD FILEGROUP Sales2018

ALTER DATABASE PartitionedData
ADD FILEGROUP Sales2019

ALTER DATABASE PartitionedData
ADD FILEGROUP Sales2020

